version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: "database"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "web-api"
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: postgres
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
