DROP TYPE IF EXISTS users_type CASCADE;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS test_passages CASCADE;
DROP TABLE IF EXISTS tests;
