db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  dbname: "postgres"
  sslmode: "disable"
  max_connections: "10"

server:
  port: 8080

cache:
  ttl: 1h

audit_logger:
  db:
    host: "127.0.0.1"
    port: 27017

  server:
    host: "127.0.0.1"
    port: 9000
